### PR TITLE
Report price range more precisely

### PR DESCRIPTION
**Pull request by fechan**
This makes the data provider assume the price range of the business based on the Yelp $$$ notation. The ranges are based on the following research article: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0252157

This is not super precise. More discussion in issue #37

### CODE REVIEW

**Comment by ssexton1** [comment]
We might want some more input but would it be better to just show the $, $$ dollar sign values. I don't have too much preference I just feel it might be easier to tell at a glance when trying to look at a card quickly.

**Comment by fechan** [comment]
I think that's gonna need client side changes, since we'd need to change the conzensus API. I'm fine with either really.

**Comment by ssexton1** [comment]
I feel like another benefit of dollar signs is we might not have to update with time due to changes in Yelps ratings since with inflation they might change over time. Let's check with Lisette after class on what she would prefer for the front-end though

**Review by ssexton1 — APPROVED** [review]

**Comment by fechan** [comment]
Changed to just respond with $$$ etc.

**Pull request merged**
