### PR TITLE
playerList now response to addPlayer call instead of joinRoom

### PR DESCRIPTION
**Pull request by ssexton1**
This was a change requested by Lisette that should make it a little easier on the frontend to make sure everyone keeps track of the correct PlayerList

Changed player list to be returned when a new player is added

Removed automatic remove player call from onAddPlayer. I had this to make sure every user only had 1 player/character associated with them but I think the only case this would be an issue is if someone clicks the back arrow where it would likely make more sense for the front end to call the remove player or for the player to disconnect from the room based on where the back arrow leads to.

### CODE REVIEW

**Review by fechan — APPROVED** [review]
Seems fine. If we're relying on the front end to disconnect from the room, maybe the back end should fail any requests to join another room if the player is already in one? So we'd send `success: false` in the `joinRoomStatus` message.

**Comment by ssexton1** [comment]
Would it make more sense to just disconnect from the old room automatically before connecting to the new one if they're already in the room? I can implement either fairly easily I'm just thinking the front end might lose track of the room their stuck in and not be able to deal with the error?

**Comment by fechan** [comment]
I thought that was the purpose of calling `onRemovePlayer()`, which you removed? Maybe I'm wrong

**Comment by ssexton1** [comment]
```onRemovePlayer()``` Only removes the players character from a room currently. I thought we were doing it so people could go back and edit their character while still in the room but I just looked through how the screens are setup after what shiori did and people make a character before joining a room.

I'll do this tomorrow but I'll change it so:

- a players character is automatically added to a room during a call to ```onJoinRoom```
- I'll create a ```onCreateCharacter``` socket function instead of addPlayer to store the character a person makes/selects in character select
- I'll make it so remove player also disconnects them from the socket
- I'll update the API doc to fit with the changes

In this case I think it'd make the most sense to have the client back button call ```onRemovePlayer``` but I can make ```onJoinRoom``` check if the socket is connected to any other rooms and disconnect from them before connecting to the new room just to be safe

If you'd prefer I solve it through a status message I can do that too though. I still think I should make the changes I mentioned above though, I spent some time thinking about it and I think it'd be a lot cleaner after these changes.

**Comment by ssexton1** [comment]
I decided against merging addPlayer into joinRoom as the host needs to make a room before having a character so it didn't make as much sense.

**Review by LisetteRinnen — APPROVED** [review]

**Pull request merged**
